config/routes.rb
Rails.application.routes.draw do
  root to: 'database#index'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :database, only: %i[index create show destroy] do
    post :anonymize
    post :download_file
    post :download_csv
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/database.rb
# frozen_string_literal: true

class Database < ApplicationRecord
  belongs_to :user
  has_many :anonymized, class_name: 'Database', foreign_key: 'original_id', dependent: :delete_all
  belongs_to :original, class_name: 'Database', optional: true

  enum dbms_type: { sqlite: 0, csv: 1 }
  mount_uploader :file, FileUploader

  STRATEGIES = {
    first_name:  FieldStrategy::RandomFirstName.new,
    last_name:   FieldStrategy::RandomLastName.new,
    full_name:   FieldStrategy::RandomFullName.new,
    date_time:   FieldStrategy::DateTimeDelta.new(2, 0),
    address:     FieldStrategy::RandomAddress.region_US,
    city:        FieldStrategy::RandomCity.region_US,
    zip_code:    FieldStrategy::RandomZipcode.region_US,
    province:    FieldStrategy::RandomProvince.region_US,
    phone:       FieldStrategy::RandomPhoneNumber.new,
    email:       FieldStrategy::RandomEmail.new,
    big_decimal: FieldStrategy::RandomBigDecimalDelta.new,
    bool:        FieldStrategy::RandomBoolean.new,
    integer:     FieldStrategy::RandomInteger.new,
    float:       FieldStrategy::RandomFloat.new,
    string:      FieldStrategy::RandomString.new,
    url:         FieldStrategy::RandomUrl.new
  }.freeze

  def sqlite_database
    SQLite3::Database.new(file.file.file)
  end

  def table_names
    sqlite_database.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';").flatten
  end

  def table_columns(table_name)
    sqlite_database.table_info(table_name).map { |table| table['name'] }
  end

  def table_data(table_name)
    sqlite_database.execute("SELECT * FROM #{table_name}")
  end

  def get_pk_column_name(table_name)
    if (pk_column = sqlite_database.table_info(table_name).find { |column| column['pk'] == 1 })
      return pk_column['name']
    end

    if (pk_column = sqlite_database.table_info(table_name).find { |column| column['name'].include? '_id' })
      return pk_column['name']
    end

    sqlite_database.table_info(table_name).first['name']
  end

  def call_anonymize(params)
    new_database = Database.create!(attributes.merge(id: nil, original: self, file: file))
    old_database = self

    database new_database.file.identifier do
      strategy DataAnon::Strategy::Blacklist
      source_db adapter: 'sqlite3', database: "public#{new_database.file.url}"
      destination_db adapter: 'sqlite3', database: "public#{old_database.file.url}"

      table params['table_name'] do
        primary_key params['primary_key']

        params['strategies'].each_key do |column_name|
          strategy_name = params['strategies'][column_name].to_sym
          anonymize(column_name).using STRATEGIES[strategy_name]
        end
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :databases
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/database_controller.rb
# frozen_string_literal: true

class DatabaseController < ApplicationController
  before_action :authenticate_user!
  before_action :database, only: %i[destroy anonymize download_file show download_csv]
  skip_before_action :verify_authenticity_token, only: %i[anonymize]

  def index
    @databases = Database.where(user: current_user, original_id: nil)
    @anonymized_databases = Database.where(user: current_user).where.not(original_id: nil)
  end

  def show
    @tables_names = @database.table_names
    @current_table_name = params[:table_name] || @tables_names[0]
    @current_table_columns = @database.table_columns(@current_table_name)
    @current_table_data = @database.table_data(@current_table_name)
    @current_table_primary_key = @database.get_pk_column_name(@current_table_name)
  end

  def create
    @database = Database.new(database_params.merge(user: current_user))
    if @database.save
      helpers.convert_csv_to_sqlite(@database) if @database.csv?
      redirect_to root_path, notice: 'Your database successful added'
    else
      redirect_to root_path, alert: 'Your database not added'
    end
  end

  def destroy
    if @database.destroy
      redirect_to root_path, notice: 'Your database successfully deleted'
    else
      redirect_to root_path, notice: "Your database wasn't deleted"
    end
  end

  def anonymize
    if @database.call_anonymize(database_anonymize_params)
      render json: { success: true }
    else
      render json: { success: false }
    end
  end

  def download_file
    send_file(@database.file.file.file)
  end

  def download_csv
    table_data = @database.table_data(params[:table_name])
    csv_file_name = "public/uploads/#{@database.file.identifier.split('.').first}.csv"

    File.write(csv_file_name, table_data.map(&:to_csv).join)
    send_file(csv_file_name)
  end

  private

  def database
    @database = Database.find(params[:database_id] || params[:id])
    redirect_to root_path, alert: "It's not your database" unless current_user.id == @database.user_id
  end

  def database_params
    params.require(:database).permit(:dbms_type, :file)
  end

  def database_anonymize_params
    params.require(:database).permit(:table_name, :primary_key, strategies: {})
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/database_helper.rb
# frozen_string_literal: true

module DatabaseHelper
  require 'csv'
  require 'sequel'

  def convert_csv_to_sqlite(database_csv)
    database_tmp_path = "#{database_csv.file.identifier}.sqlite"
    gem_db = get_sequel_database(database_tmp_path)

    populate_table_from_csv(gem_db, database_csv.file.file.file)

    database_csv.update(file: File.open(database_tmp_path))
    File.delete(database_tmp_path)
  end

  def get_sequel_database(filename)
    puts "Connecting to sqlite://#{filename}"
    Sequel.sqlite(filename)
  end

  def populate_table_from_csv(database, filename)
    options = { headers:           true,
                header_converters: :symbol,
                converters:        :all }
    data = CSV.table(filename, options)
    headers = data.headers
    table_name = File.basename(filename, '.csv').gsub(/[^0-9a-zA-Z_]/, '_').to_sym

    puts "Dropping and re-creating table #{table_name}"
    database.drop_table? table_name
    database.create_table table_name do
      # see http://sequel.rubyforge.org/rdoc/files/doc/schema_modification_rdoc.html
      # primary_key :id
      # Float :price
      data.by_col!.each do |column_name, _rows|
        # column_type = get_common_class(rows) || String
        column(column_name, String)
      end
    end
    data.by_row!.each do |row|
      database[table_name].insert(row.to_hash)
    end
  end

  #
  # :call-seq:
  #   getCommonClass([1,2,3])         => FixNum
  #   getCommonClass([1,"bob",3])     => String
  #
  # Returns the class of each element in +rows+ if same for all elements, otherwise returns nil
  #
  def get_common_class(rows)
    rows.map(&:class).max_by { |i| rows.map(&:class).count(i) }
  end
end

app/views/database/index.html.haml
.pull-right.my-3
  %button.btn.btn-primary{"data-bs-target" => "#create-database-modal", "data-bs-toggle" => "modal"}
    Add database
#create-database-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "create-database-modal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title Add new database
      = form_with model: Database.new, url: database_index_path do |f|
        .modal-body
          .row
            .col-9
              = f.label :file
            .col-3
              = f.label :file_type
          .row
            .col-9
              = f.file_field :file, class: 'mw-100'
            .col-3
              = f.select :dbms_type, options_for_select(Database.dbms_types.keys)
        .modal-footer
          = f.submit("Create", class: "btn-primary btn")

- if @databases.length == 0
  %h5 Your databases list is empty
- else
  %h5 Your databases
  %table.table.table-hover
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Type
        %th{:scope => "col"} Tables
    %tbody
      - @databases.each_with_index do |database_item, index|
        %tr
          %th{:scope => "row"} #{index+1}
          %td #{database_item.file.identifier}
          %td #{database_item.dbms_type}
          %td #{database_item.table_names}
          %td
            = link_to "View & Anonymize", database_path(database_item), class: 'btn btn-info'
          %td
            = link_to "Delete", database_path(database_item), class: 'btn btn-danger', method: :delete

- if @anonymized_databases.length == 0
  %h5 Your anonymized databases list is empty
- else
  %h5 Your anonymized databases
  %table.table.table-hover
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Type
        %th{:scope => "col"} Tables
    %tbody
      - @anonymized_databases.each_with_index do |database_item, index|
        %tr
          %th{:scope => "row"} #{index+1}
          %td #{database_item.file.identifier}
          %td #{database_item.dbms_type}
          %td #{database_item.table_names}
          %td
            = link_to "View & Download", database_path(database_item), class: 'btn btn-info'
          %td
            = link_to "Delete", database_path(database_item), class: 'btn btn-danger', method: :delete

app/views/database/show.html.haml
.d-flex.justify-content-between.my-2
  .align-items-center.d-flex
    Choose table:
    .mx-4
      = select_tag(:table_name, options_for_select(@tables_names, @current_table_name), onchange: "handleTableName()")

  = react_component('AnonymizeSection', { database: @database,
                                    currentTableName: @current_table_name,
                                    currentTableColumns: @current_table_columns,
                                    currentTablePrimaryKey: @current_table_primary_key,
                                  }, prerender: false)
  .d-flex
    = form_with url: database_download_file_path(@database) do |f|
      = f.submit("Download sqlite", class: "btn-warning btn")
    = form_with url: database_download_csv_path(@database, table_name: @current_table_name) do |f|
      = f.submit("Convert table to CSV", class: "btn-success btn")

%table#myTable
  %thead
    %tr
      - @current_table_columns.each do |header|
        %th.text-truncate #{header}
  %tbody
    - @current_table_data.each do |row|
      %tr
        - row.each do |item|
          %td #{item}

:javascript
  $(document).ready( function () {
      $('#myTable').DataTable()
    });

  function handleTableName() {
    let selectValue = $("#table_name option:selected").text()
    const url = new URL(location.href);
    url.searchParams.set('table_name', selectValue);
    window.location.href = url;
  }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DataAnonymizator
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render "partials/header"
    = render "partials/flash_message"
    = yield

app/views/partials/_flash_message.html.haml
- if notice
  #success-alert.alert.alert-success
    %strong
      =notice
- if alert
  #danger-alert.alert.alert-danger
    %strong
      =alert

:javascript
  $("#success-alert").fadeTo(3000, 500).slideUp(500, function(){
  $("#success-alert").slideUp(500);
  });
  $("#danger-alert").fadeTo(3000, 500).slideUp(500, function(){
  $("#danger-alert").slideUp(500);
  });

app/views/partials/_header.html.haml
- if current_user
  %nav.navbar.navbar-light.bg-light
    %a.navbar-brand{:href => root_path} Data Anonymizator
    .pull_right
      .btn-group.dropleft
        %button.btn.btn-secondary
          = current_user.email
        = link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-info'